on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Current location
        run: pwd

      - name: 'Saying Hi'
        run: echo Hi 

      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Show repository content'
        run: ls -la

      - name: 'Log in to DockerHub'
        run: echo "${{ secrets.TOKEN }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

      - name: 'Build the Docker image'
        run: docker build -t ${{ secrets.USERNAME }}/yara3:latest .

      - name: 'Push the Docker image'
        run: docker push ${{ secrets.USERNAME }}/yara3:latest
