on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Current location'
        run: pwd 
      
      - name: 'Saying Hi'
        run: echo Hi

      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'content'
        run: pwd  
      
      - name: 'Log in to DockerHub'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.TOKEN }}

      - name: 'Build the image to docker'
        run: docker build -t ${{ secrets.USERNAME }}/yara3 .

      - name: 'Push the image'
        run: docker push ${{ secrets.USERNAME }}/yara3
